# Generated by Django 5.2 on 2025-04-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='periodo',
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Lista',
        ),
    ]
