# Generated by Django 5.2 on 2025-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='color',
            field=models.CharField(default='azul', help_text='Color representativo de la lista (nombre o código hexadecimal)', max_length=20),
        ),
    ]
