# Generated by Django 5.2 on 2025-05-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0004_lista_color'),
        ('padron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='padron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='padron.padronelectoral'),
        ),
    ]
