# Generated by Django 5.2 on 2025-06-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0006_alter_candidato_options_candidato_tipo_candidato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={},
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tipo_candidato',
            field=models.CharField(blank=True, choices=[('PRINCIPAL', 'Principal'), ('SUPLENTE', 'Suplente'), ('ALTERNO', 'Alterno')], default='PRINCIPAL', max_length=20, null=True),
        ),
    ]
