# Generated by Django 5.2 on 2025-06-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0007_alter_candidato_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='cedula_alterno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del alterno'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='cedula_principal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del candidato principal'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='cedula_suplente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del suplente'),
        ),
    ]
