# Generated by Django 5.1.5 on 2025-04-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_1', models.ImageField(upload_to='logos/')),
                ('logo_2', models.ImageField(upload_to='logos/')),
                ('iniciales', models.CharField(max_length=10)),
            ],
        ),
    ]
