# Generated by Django 5.1.5 on 2025-04-16 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogoConfig',
        ),
    ]
