# Generated by Django 5.1.5 on 2025-04-09 04:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados', to='periodo.periodo', verbose_name='Período académico')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, verbose_name='Letra del paralelo')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='padron.grado', verbose_name='Grado asociado')),
            ],
            options={
                'verbose_name': 'Paralelo',
                'verbose_name_plural': 'Paralelos',
                'ordering': ['grado', 'nombre'],
                'unique_together': {('nombre', 'grado')},
            },
        ),
        migrations.CreateModel(
            name='PadronElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula de identidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('activo', 'Activo - Puede votar'), ('inactivo', 'Inactivo - No puede votar')], default='activo', max_length=10, verbose_name='Estado en el padrón')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padron.grado', verbose_name='Grado del estudiante')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padron_electoral', to='periodo.periodo', verbose_name='Período académico')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padron.paralelo', verbose_name='Paralelo del estudiante')),
            ],
            options={
                'verbose_name': 'Registro electoral',
                'verbose_name_plural': 'Padrón electoral',
                'ordering': ['apellidos', 'nombre'],
                'unique_together': {('cedula', 'periodo'), ('correo', 'periodo')},
            },
        ),
    ]
