# Generated by Django 5.2 on 2025-06-10 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=10, unique=True, verbose_name='Nombre de usuario')),
                ('contrasena', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cambiada', 'Contraseña cambiada')], default='activo', max_length=10, verbose_name='Estado de la credencial')),
                ('padron', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial', to='padron.padronelectoral', verbose_name='Registro del padrón')),
            ],
            options={
                'verbose_name': 'Credencial de usuario',
                'verbose_name_plural': 'Credenciales de usuarios',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
