# Generated by Django 5.2 on 2025-06-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0002_credencialusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credencialusuario',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='credencialusuario',
            name='_contrasena_plana',
            field=models.CharField(blank=True, help_text='Se almacena temporalmente para mostrarla al administrador', max_length=128, null=True, verbose_name='Contraseña (texto plano)'),
        ),
        migrations.AddField(
            model_name='credencialusuario',
            name='contrasena_encriptada',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña (encriptada)'),
        ),
    ]
