# Generated by Django 5.2.3 on 2025-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(blank=True, help_text='Resumen breve de la noticia (máx. 500 caracteres)', max_length=500, null=True, verbose_name='Resumen'),
        ),
    ]
