# Generated by Django 5.2.3 on 2025-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='visitas',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Número de visitas'),
        ),
    ]
