# Generated by Django 5.2.3 on 2025-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticia_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la noticia (recomendado 1200x630px)', null=True, upload_to='noticias/', verbose_name='Imagen'),
        ),
    ]
