# Generated by Django 5.2.3 on 2025-07-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_noticia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
    ]
