# Generated by Django 5.2.3 on 2025-07-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_remove_noticia_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='color',
        ),
    ]
