# Generated by Django 5.2 on 2025-05-13 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0005_candidato_padron'),
        ('padron', '0001_initial'),
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodo.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_nulo', models.BooleanField(default=False)),
                ('es_blanco', models.BooleanField(default=False)),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('hash_voto', models.CharField(max_length=64, unique=True)),
                ('lista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elecciones.lista')),
                ('proceso_electoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacion.procesoelectoral')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padron.padronelectoral')),
            ],
            options={
                'unique_together': {('proceso_electoral', 'votante')},
            },
        ),
    ]
