# Generated by Django 5.2 on 2025-05-13 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0001_initial'),
        ('votacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='votante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='padron.padronelectoral'),
        ),
    ]
