# Generated by Django 5.2 on 2025-05-13 03:32

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0002_alter_voto_votante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesoelectoral',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='procesoelectoral',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='procesoelectoral',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de las elecciones'),
        ),
        migrations.AddField(
            model_name='procesoelectoral',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Hora de finalización de las elecciones'),
        ),
        migrations.AddField(
            model_name='procesoelectoral',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Hora de inicio de las elecciones'),
        ),
    ]
