# Generated by Django 5.2 on 2025-07-01 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0003_remove_procesoelectoral_fecha_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnetVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(help_text='Código QR único para verificar el voto', max_length=100, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('es_valido', models.BooleanField(default=True, help_text='Indica si el carnet es válido')),
                ('voto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carnet', to='votacion.voto', verbose_name='Voto asociado')),
            ],
            options={
                'verbose_name': 'Carnet de Votación',
                'verbose_name_plural': 'Carnets de Votación',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
