# Generated by Django 5.2.3 on 2025-07-01 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0004_carnetvotacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnetvotacion',
            name='es_valido',
        ),
        migrations.AddField(
            model_name='carnetvotacion',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carnetvotacion',
            name='codigo_verificacion',
            field=models.CharField(blank=True, help_text='Código único para verificar el voto', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carnetvotacion',
            name='fecha_votacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carnetvotacion',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carnetvotacion',
            name='proceso_electoral',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carnetvotacion',
            name='codigo_qr',
            field=models.CharField(blank=True, help_text='Código QR del voto', max_length=255),
        ),
        migrations.AlterField(
            model_name='carnetvotacion',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carnetvotacion',
            name='voto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carnet', to='votacion.voto'),
        ),
    ]
