# Generated by Django 5.1 on 2025-07-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0005_remove_carnetvotacion_es_valido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnetvotacion',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la verificación', null=True),
        ),
        migrations.AddField(
            model_name='carnetvotacion',
            name='utilizado',
            field=models.BooleanField(default=False, help_text='Indica si el carnet ha sido verificado'),
        ),
    ]
