# Generated by Django 5.1.5 on 2025-04-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_periodo_alter_usuarios_id_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
