# Generated by Django 5.2 on 2025-04-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarios_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.roles'),
        ),
    ]
