# Generated by Django 5.2 on 2025-07-01 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0003_remove_credencialusuario_contrasena_and_more'),
        ('usuarios', '0004_alter_usuarios_id_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='padron_electoral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='padron.padronelectoral', verbose_name='Registro en el padrón electoral'),
        ),
    ]
