# Generated by Django 5.2.3 on 2025-07-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuarios_padron_electoral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='padron_electoral',
        ),
    ]
