# Generated by Django 5.2.3 on 2025-07-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuarios_padron_electoral'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='primer_inicio',
            field=models.BooleanField(default=True),
        ),
    ]
